title: SpectraGuru Documentation
description: SpectraGuru Documentation page!
theme: just-the-docs
favicon_ico: "/assets/images/favicon.png"
logo: "/assets/images/logo.png"

url: https://github.com/FengboMa/docs.spectraguru

# aux_links:
#   Template Repository: https://github.com/just-the-docs/just-the-docs-template
